git:
  depth: 1
language: node_js
node_js:
- '4'
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 178.62.41.238
before_script:
- npm install -g npm
- npm install -g gulp-cli
- chmod +x ./deploy-gh-pages.sh
script: "./deploy-gh-pages.sh"
env:
  global:
